---
abstract: 'Processing PYX data or file and write as SGML.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.07
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 1.02
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PYX-SGML-Raw
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.05
  PYX::Parser: 0.01
  PYX::Utils: 0.01
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/PYX-SGML-Raw/issues
  homepage: https://github.com/michal-josef-spacek/PYX-SGML-Raw
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/PYX-SGML-Raw
version: '0.05'
